#include "Geometry.hpp"
#include <algorithm>
#include <array>
#include <cmath>
#include <limits>
#include <set>
#include <unordered_set>
namespace { constexpr float PI=3.14159265358979323846f;
float dot(V4 a,V4 b){return a.x*b.x+a.y*b.y+a.z*b.z+a.w*b.w;} float len(V4 a){return std::sqrt(dot(a,a));}
V4 norm4(V4 a){float q=len(a); return q>1e-12f?V4{a.x/q,a.y/q,a.z/q,a.w/q}:V4{0,0,0,1};}
float d4(V4 a,V4 b){return len({a.x-b.x,a.y-b.y,a.z-b.z,a.w-b.w});}
V4 rot(V4 q,int a,int b,float t){float* z=&q.x;float c=std::cos(t),s=std::sin(t),A=z[a],B=z[b];z[a]=c*A-s*B;z[b]=s*A+c*B;return q;}
void inferEdges(Polytope4&p){p.e.clear();float md=std::numeric_limits<float>::max();for(size_t i=0;i<p.v.size();++i)for(size_t j=i+1;j<p.v.size();++j){float d=d4(p.v[i],p.v[j]);if(d>1e-5f)md=std::min(md,d);}float tol=std::max(1e-5f,md*2e-3f);for(uint32_t i=0;i<p.v.size();++i)for(uint32_t j=i+1;j<p.v.size();++j)if(std::fabs(d4(p.v[i],p.v[j])-md)<=tol)p.e.push_back({i,j});}
void inferTriFaces(Polytope4&p){p.faces.clear();size_t n=p.v.size();std::vector<std::unordered_set<uint32_t>> adj(n);for(auto e:p.e){adj[e.a].insert(e.b);adj[e.b].insert(e.a);}for(uint32_t a=0;a<n;a++)for(uint32_t b:adj[a])if(a<b)for(uint32_t c:adj[a])if(b<c&&adj[b].count(c))p.faces.push_back({a,b,c});}
void gridEdges(Mesh3&m,unsigned U,unsigned V,bool wrapU,bool wrapV){for(unsigned u=0;u<U;u++)for(unsigned v=0;v<V;v++){uint32_t i=u*V+v;if(wrapU||u+1<U)m.e.push_back({i,((u+1)%U)*V+v});if(wrapV||v+1<V)m.e.push_back({i,u*V+(v+1)%V});}}
float sf(float a,float m,float n1,float n2,float n3){float t=m*a/4.f;return std::pow(std::pow(std::fabs(std::cos(t)),n2)+std::pow(std::fabs(std::sin(t)),n3),-1.f/n1);}
V3 chart(V4 q,V4 n){int drop=0;float a[4]={std::fabs(n.x),std::fabs(n.y),std::fabs(n.z),std::fabs(n.w)};for(int i=1;i<4;i++)if(a[i]>a[drop])drop=i;float z[4]={q.x,q.y,q.z,q.w},o[3];int k=0;for(int i=0;i<4;i++)if(i!=drop)o[k++]=z[i];return {o[0],o[1],o[2]};}
uint32_t addVertex(Mesh3&m,V3 p,float eps=1e-5f){for(uint32_t i=0;i<m.v.size();i++){V3 q=m.v[i];float dx=p.x-q.x,dy=p.y-q.y,dz=p.z-q.z;if(dx*dx+dy*dy+dz*dz<eps*eps)return i;}m.v.push_back(p);return uint32_t(m.v.size()-1);}
}
namespace geo {
Mesh3 cube(float s){Mesh3 m;for(int i=0;i<8;i++)m.v.push_back({(i&1)?s:-s,(i&2)?s:-s,(i&4)?s:-s});for(uint32_t i=0;i<8;i++)for(int b=0;b<3;b++){uint32_t j=i^(1u<<b);if(i<j)m.e.push_back({i,j});}return m;}
Mesh3 uvSphere(unsigned R,unsigned S,float r){R=std::max(2u,R);S=std::max(3u,S);Mesh3 m;for(unsigned y=0;y<=R;y++){float p=PI*y/R;for(unsigned x=0;x<S;x++){float t=2*PI*x/S;m.v.push_back({r*std::sin(p)*std::cos(t),r*std::cos(p),r*std::sin(p)*std::sin(t)});}}for(unsigned y=0;y<=R;y++)for(unsigned x=0;x<S;x++){uint32_t i=y*S+x;m.e.push_back({i,y*S+(x+1)%S});if(y<R)m.e.push_back({i,(y+1)*S+x});}return m;}
Mesh3 torus(unsigned A,unsigned B,float R,float r){A=std::max(3u,A);B=std::max(3u,B);Mesh3 m;for(unsigned a=0;a<A;a++)for(unsigned b=0;b<B;b++){float u=2*PI*a/A,v=2*PI*b/B;m.v.push_back({(R+r*std::cos(v))*std::cos(u),r*std::sin(v),(R+r*std::cos(v))*std::sin(u)});}gridEdges(m,A,B,true,true);return m;}
Mesh3 boySurface(unsigned U,unsigned V,float scale){U=std::max(8u,U);V=std::max(4u,V);Mesh3 m;for(unsigned i=0;i<U;i++)for(unsigned j=0;j<V;j++){float u=PI*i/U,v=2*PI*j/V;float cu=std::cos(u),s2=std::sqrt(2.f);float den=2.f-s2*std::sin(3*u)*std::sin(2*v);float x=(s2*cu*cu*std::cos(2*v)+cu*std::sin(2*v))/den;float y=(s2*cu*cu*std::sin(2*v)-cu*std::cos(2*v))/den;float z=(3.f*cu*cu)/den-1.f;m.v.push_back({scale*x,scale*y,scale*z});}gridEdges(m,U,V,true,true);return m;}
Mesh3 hopfFibres(unsigned F,unsigned S,float pw){F=std::max(2u,F);S=std::max(12u,S);Mesh3 m;for(unsigned f=0;f<F;f++){float a=2*PI*f/F;float eta=.18f+1.18f*(f+.5f)/F;for(unsigned s=0;s<S;s++){float t=2*PI*s/S;V4 q{std::cos(eta)*std::cos(t),std::cos(eta)*std::sin(t),std::sin(eta)*std::cos(t+a),std::sin(eta)*std::sin(t+a)};float k=pw/(pw-q.w);m.v.push_back({q.x*k,q.y*k,q.z*k});}for(unsigned s=0;s<S;s++)m.e.push_back({f*S+s,f*S+(s+1)%S});}return m;}
Mesh3 superformula(unsigned U,unsigned V,float m1,float m2,float n1,float n2,float n3){U=std::max(8u,U);V=std::max(4u,V);Mesh3 m;for(unsigned i=0;i<U;i++)for(unsigned j=0;j<V;j++){float lon=-PI+2*PI*i/U,lat=-PI/2+PI*j/(V-1);float r1=sf(lon,m1,n1,n2,n3),r2=sf(lat,m2,n1,n2,n3);m.v.push_back({r1*std::cos(lon)*r2*std::cos(lat),r1*std::sin(lon)*r2*std::cos(lat),r2*std::sin(lat)});}gridEdges(m,U,V,true,false);return m;}
Polytope4 tesseract(float s){Polytope4 p;for(int i=0;i<16;i++)p.v.push_back({(i&1)?s:-s,(i&2)?s:-s,(i&4)?s:-s,(i&8)?s:-s});for(uint32_t i=0;i<16;i++)for(int b=0;b<4;b++){uint32_t j=i^(1u<<b);if(i<j)p.e.push_back({i,j});}for(int a=0;a<4;a++)for(int b=a+1;b<4;b++)for(int mask=0;mask<16;mask++)if(!(mask&(1<<a))&&!(mask&(1<<b))){uint32_t q=mask,r=q|(1u<<a),s0=r|(1u<<b),t=q|(1u<<b);p.faces.push_back({q,r,s0,t});}return p;}
Polytope4 cell16(float s){Polytope4 p;p.v={{s,0,0,0},{-s,0,0,0},{0,s,0,0},{0,-s,0,0},{0,0,s,0},{0,0,-s,0},{0,0,0,s},{0,0,0,-s}};inferEdges(p);inferTriFaces(p);return p;}
Polytope4 cell24(float s){Polytope4 p;for(int a=0;a<4;a++)for(int b=a+1;b<4;b++)for(int sa:{-1,1})for(int sb:{-1,1}){V4 q{};float*z=&q.x;z[a]=sa*s;z[b]=sb*s;p.v.push_back(q);}inferEdges(p);inferTriFaces(p);return p;}
Polytope4 cell600(){Polytope4 p;float phi=(1+std::sqrt(5.f))/2,ip=1/phi;for(int a=0;a<4;a++)for(int s:{-1,1}){V4 q{};(&q.x)[a]=2.f*s;p.v.push_back(q);}for(int m=0;m<16;m++)p.v.push_back({(m&1)?1.f:-1.f,(m&2)?1.f:-1.f,(m&4)?1.f:-1.f,(m&8)?1.f:-1.f});std::array<float,4>b{0,1,phi,ip};std::array<int,4>pm{0,1,2,3};do{int inv=0;for(int i=0;i<4;i++)for(int j=i+1;j<4;j++)inv+=pm[i]>pm[j];if(inv&1)continue;for(int mask=0;mask<8;mask++){V4 q{};float*z=&q.x;int si=0;for(int k=0;k<4;k++){float v=b[pm[k]];if(v){if(mask&(1<<si))v=-v;si++;}z[k]=v;}p.v.push_back(q);}}while(std::next_permutation(pm.begin(),pm.end()));std::vector<V4>u;for(auto q:p.v){bool seen=false;for(auto r:u)if(d4(q,r)<1e-5f){seen=true;break;}if(!seen)u.push_back(q);}p.v=std::move(u);inferEdges(p);inferTriFaces(p);return p;}
Mesh3 project4D(const Polytope4&p,float a,float b,float cw,float xw,float yz){Mesh3 m;m.e=p.e;m.v.reserve(p.v.size());for(V4 q:p.v){q=rot(q,0,1,a);q=rot(q,2,3,b);q=rot(q,0,3,xw);q=rot(q,1,2,yz);float den=cw-q.w;if(std::fabs(den)<.05f)den=std::copysign(.05f,den);float k=cw/den;m.v.push_back({q.x*k,q.y*k,q.z*k});}return m;}
Mesh3 sliceFaces4D(const Polytope4&p,V4 n,float h,float eps){Mesh3 m;n=norm4(n);for(const Face&f:p.faces){std::vector<V4>hits;for(size_t k=0;k<f.size();k++){V4 a=p.v[f[k]],b=p.v[f[(k+1)%f.size()]];float da=dot(n,a)-h,db=dot(n,b)-h;if(std::fabs(da)<=eps)hits.push_back(a);if((da<-eps&&db>eps)||(da>eps&&db<-eps)){float t=da/(da-db);hits.push_back({a.x+t*(b.x-a.x),a.y+t*(b.y-a.y),a.z+t*(b.z-a.z),a.w+t*(b.w-a.w)});}}std::vector<uint32_t>ids;for(V4 q:hits){V3 c=chart(q,n);uint32_t id=addVertex(m,c,eps*4);if(std::find(ids.begin(),ids.end(),id)==ids.end())ids.push_back(id);}if(ids.size()==2&&ids[0]!=ids[1])m.e.push_back({ids[0],ids[1]});else if(ids.size()>2)for(size_t i=0;i<ids.size();i++)m.e.push_back({ids[i],ids[(i+1)%ids.size()]});}std::set<std::pair<uint32_t,uint32_t>>seen;std::vector<Edge>e;for(auto x:m.e){auto q=std::minmax(x.a,x.b);if(q.first!=q.second&&seen.insert(q).second)e.push_back({q.first,q.second});}m.e=std::move(e);return m;}
Mesh3 gyroidIsosurface(unsigned n,float iso){n=std::max(4u,n);Mesh3 m;auto F=[&](float x,float y,float z){return std::sin(x)*std::cos(y)+std::sin(y)*std::cos(z)+std::sin(z)*std::cos(x)-iso;};const int tet[6][4]={{0,5,1,6},{0,1,2,6},{0,2,3,6},{0,3,7,6},{0,7,4,6},{0,4,5,6}};const int C[8][3]={{0,0,0},{1,0,0},{1,1,0},{0,1,0},{0,0,1},{1,0,1},{1,1,1},{0,1,1}};for(unsigned z=0;z<n-1;z++)for(unsigned y=0;y<n-1;y++)for(unsigned x=0;x<n-1;x++){V3 P[8];float D[8];for(int c=0;c<8;c++){float X=-PI+2*PI*(x+C[c][0])/(n-1),Y=-PI+2*PI*(y+C[c][1])/(n-1),Z=-PI+2*PI*(z+C[c][2])/(n-1);P[c]={X/PI,Y/PI,Z/PI};D[c]=F(X,Y,Z);}for(auto&T:tet){std::vector<V3>h;for(int a=0;a<4;a++)for(int b=a+1;b<4;b++){int i=T[a],j=T[b];if((D[i]<0)==(D[j]<0))continue;float t=D[i]/(D[i]-D[j]);h.push_back({P[i].x+t*(P[j].x-P[i].x),P[i].y+t*(P[j].y-P[i].y),P[i].z+t*(P[j].z-P[i].z)});}if(h.size()>=3){std::vector<uint32_t>id;for(auto q:h)id.push_back(addVertex(m,q,2e-4f));for(size_t i=0;i<id.size();i++)if(id[i]!=id[(i+1)%id.size()])m.e.push_back({id[i],id[(i+1)%id.size()]});}}}return m;}
MeshStats stats(const Mesh3&m){MeshStats s;s.vertices=m.v.size();s.edges=m.e.size();for(auto q:m.v){if(!std::isfinite(q.x)||!std::isfinite(q.y)||!std::isfinite(q.z))s.finite=false;s.radius=std::max(s.radius,std::sqrt(q.x*q.x+q.y*q.y+q.z*q.z));}for(auto e:m.e)if(e.a>=m.v.size()||e.b>=m.v.size())s.indicesValid=false;return s;}
bool validate(const Mesh3&m,std::string*w){auto s=stats(m);if(!s.finite){if(w)*w="non-finite vertex";return false;}if(!s.indicesValid){if(w)*w="edge index out of range";return false;}std::set<std::pair<uint32_t,uint32_t>> seen;for(auto e:m.e){if(e.a==e.b){if(w)*w="self edge";return false;}auto p=std::minmax(e.a,e.b);if(!seen.insert(p).second){if(w)*w="duplicate edge";return false;}}return true;}
bool validate(const Polytope4&p,std::string*w){for(auto q:p.v)if(!std::isfinite(q.x)||!std::isfinite(q.y)||!std::isfinite(q.z)||!std::isfinite(q.w)){if(w)*w="non-finite 4D vertex";return false;}for(auto e:p.e)if(e.a>=p.v.size()||e.b>=p.v.size()){if(w)*w="4D edge index out of range";return false;}for(auto&f:p.faces)for(auto i:f)if(i>=p.v.size()){if(w)*w="face index out of range";return false;}return true;}
}
